<a href="https://colab.research.google.com/github/anutishah/project_chd/blob/main/Project2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! git clone https://github.com/DS3001/project_chd


Cloning into 'project_chd'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 13 (delta 2), reused 2 (delta 1), pack-reused 9
Receiving objects: 100% (13/13), 638.41 KiB | 9.97 MiB/s, done.
Resolving deltas: 100% (4/4), done.


In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv('/content/project_chd/fhs_train.csv')
df.head()

Unnamed: 0  sex  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1267    1   58        1.0              0         0.0     0.0   
1        1209    0   40        1.0              1        15.0     0.0   
2        2050    0   52        1.0              0         0.0     0.0   
3        1183    1   38        2.0              1        43.0     0.0   
4        3225    0   43        1.0              0         0.0     0.0   

   prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                0             0         0    220.0  143.0  104.0  29.85   
1                0             0         0    199.0  122.0   82.0  22.16   
2                0             0         0    275.0  112.0   71.0  25.68   
3                0             1         0    170.0  130.0   94.0  23.90   
4                0             0         0    202.0  124.0   92.0  21.26   

   heartRate  glucose  TenYearCHD  
0         75     87.0           1  
1         85     77.0           0  
2         80      NaN           0  
3        110     75.0           0  
4         75     74.0           0

In [9]:
df.shape

(3180, 17)

In [5]:
df.dtypes

Unnamed: 0           int64
sex                  int64
age                  int64
education          float64
currentSmoker        int64
cigsPerDay         float64
BPMeds             float64
prevalentStroke      int64
prevalentHyp         int64
diabetes             int64
totChol            float64
sysBP              float64
diaBP              float64
BMI                float64
heartRate            int64
glucose            float64
TenYearCHD           int64
dtype: object

In [4]:
hr = df['heartRate']
hr.unique()

array([ 75,  85,  80, 110,  91,  63,  70,  44, 103,  58,  74,  95,  78,
        60,  81,  68,  79, 100,  72,  93,  66,  77,  69,  76,  65,  67,
        54,  62,  90,  73, 120, 106, 115,  50,  64,  82,  98,  57,  83,
        88,  84,  86,  92,  56,  96,  94,  87, 108,  55,  71,  52, 102,
       107,  51,  61,  53,  89, 105,  59, 140, 104,  99, 125, 112, 122,
        48,  46,  97,  47, 130])

In [7]:
chol = df['totChol']
chol.unique()

array([220., 199., 275., 170., 202., 232., 237., 254., 332., 259., 229.,
       315., 257., 214., 261., 210., 309., 247., 193., 285., 179., 184.,
       207., 256., 180., 301., 240., 152., 219., 290., 311., 148., 276.,
       160., 194., 252., 230., 201., 322., 238., 288., 246., 267., 283.,
       228., 186., 159., 277., 342., 292., 213., 270., 185., 175., 233.,
       336., 171., 221., 218., 225., 263., 216., 200., 187., 340., 273.,
       241., 296., 212., 196., 192., 354., 260., 189., 258., 250., 334.,
       183., 265., 209., 195., 243., 222., 271., 289., 347., 321., 150.,
       299., 206., 167., 165., 302., 231., 266., 204., 223., 272., 198.,
       236., 235., 215., 156., 155., 300., 217., 280., 245., 262., 305.,
       306., 269., 203., 390., 325., 211., 242., 350., 314., 323., 234.,
       190., 287., 328., 268., 188., 304., 205., 294., 174., 297., 293.,
       278.,  nan, 227., 172., 329., 249., 244., 178., 154., 248., 239.,
       251., 286., 226., 346., 153., 312., 282., 25

In [10]:
chol_NA = chol.isnull()
print(np.sum(chol_NA),'\n') #only 39 nan values out of ~3000
chol = chol.dropna()

39 



In [11]:
chol.unique()

array([220., 199., 275., 170., 202., 232., 237., 254., 332., 259., 229.,
       315., 257., 214., 261., 210., 309., 247., 193., 285., 179., 184.,
       207., 256., 180., 301., 240., 152., 219., 290., 311., 148., 276.,
       160., 194., 252., 230., 201., 322., 238., 288., 246., 267., 283.,
       228., 186., 159., 277., 342., 292., 213., 270., 185., 175., 233.,
       336., 171., 221., 218., 225., 263., 216., 200., 187., 340., 273.,
       241., 296., 212., 196., 192., 354., 260., 189., 258., 250., 334.,
       183., 265., 209., 195., 243., 222., 271., 289., 347., 321., 150.,
       299., 206., 167., 165., 302., 231., 266., 204., 223., 272., 198.,
       236., 235., 215., 156., 155., 300., 217., 280., 245., 262., 305.,
       306., 269., 203., 390., 325., 211., 242., 350., 314., 323., 234.,
       190., 287., 328., 268., 188., 304., 205., 294., 174., 297., 293.,
       278., 227., 172., 329., 249., 244., 178., 154., 248., 239., 251.,
       286., 226., 346., 153., 312., 282., 253., 31

In [12]:
chd = df['TenYearCHD']
chd.unique()

array([1, 0])